name: rcaferati_flutter_awesome_button_example
description: Example app for rcaferati_flutter_awesome_button.
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  rcaferati_flutter_awesome_button:
    path: ../
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/characters/
